### ISSUE TITLE
Multiview4 label's not changing.

### ISSUE THREAD

**Issue by tcconway** [bitfocus/companion-module-bmd-multiview4#2]
Hi guys.
I can't seem to get the "source labels" to change. Assuming this will change the UMD Label for each split, correct?
Thanks!
![button](https://user-images.githubusercontent.com/403326/66156419-9ddd9600-e5ef-11e9-8299-2165d0ffe006.png)

**Comment by peternewman** [comment]
This works for me after #13 is in, probably via https://github.com/bitfocus/companion-module-bmd-multiview4/pull/13/commits/1ca87cc35100fe76718c04d44d928272535d44e2

I suspect it might actually be working anyway and just not updating in Companion, although presumably you were looking at the output?

**Comment by peternewman** [comment]
I can confirm this pushes all the way to the device since #13 has been merged, closing this too.
