### ISSUE TITLE
BMD Multiview 4 - SOLO Display Mode

### ISSUE THREAD

**Issue by pizcollection** [bitfocus/companion-module-bmd-multiview4#4]
Hi,
I have been using this module for a while and it works great mostly, but I noticed an issue when trying to switch between SOLO and 2x2 Modes. I tried with different configurations, but nothing happens when pressing those buttons. When using the Blackmagic Multiview Software switching between modes works great. Any suggestion? 
Thanks in advance!

**Comment by TheSashmo** [comment]
Where are the options for the layout and solo?  When I got to the editor to add the buttons, it only gives me the routing style buttons, but no configuration buttons, am I looking in the wrong spot?

**Comment by SlipstreamCoding** [comment]
The SOLO and 2x2 buttons still don't work :-(

**Comment by peternewman** [comment]
Is this the same as #9 ? Do you mean when you add a preset? Building the button manually should fix it if so.

**Comment by peternewman** [comment]
I believe this is all fixed with #13.
