### ISSUE TITLE
Unable to change output Video Format setting

### ISSUE THREAD

**Issue by bjeans** [bitfocus/companion-module-bmd-multiview4#5]
I'm trying to get this module to change the Video Format (output) of the Multiview4

The valid configuration stanza's are below and each work if sent over telnet connection to the BMD Multiview4

CONFIGURATION:
Output format: 1080i50

CONFIGURATION:
Output format: 1080i5994

CONFIGURATION:
Output format: 2160p25

CONFIGURATION:
Output format: 2160p2997

I can't figure out from the code how I would go about changing / updating this module to support these setting as the current setting (50i/50p/60i/60p) don't seem to do anything.

I'm happy to hack away at the code if someone can point me in the right direction - is it as simple as changing the this.CHOICES_OUTPUTFORMAT array in index.js?  if so, which field is what is actually sent to the device?

**Comment by ColinMulcahy** [comment]
Has this update been implemented?
