### ISSUE TITLE
Preset Issue

### ISSUE THREAD

**Issue by hadphild** [bitfocus/companion-module-bmd-multiview4#9]
The Display 2x2  presets has a bug and is Solo not 2x2 in the Config

**Comment by SlipstreamCoding** [comment]
EDIT: 
it seems if you add the buttons manually and not from preset it works.

**Comment by peternewman** [comment]
This is fixed by this commit in #13 
https://github.com/bitfocus/companion-module-bmd-multiview4/pull/13/commits/b3daf8dad3554532fbb7c38d8e7e19114cedf190
